apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: devops-bao
spec:
  provider:
    vault:
      server: "http://devops-openbao-openbao.devops-openbao.svc.cluster.local:8200"
      path: "k8s"
      version: "v1"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-k8s
  conditions:
    - namespaces:
        - flux-system
        - devops-db
        - devops-keycloak
