apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ${cluster_name}-bao
spec:
  provider:
    vault:
      server: "http://${cluster_name}-openbao-openbao.${cluster_name}-openbao.svc.cluster.local:8200"
      path: "k8s"
      version: "v1"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-k8s
  conditions:
    - namespaces:
        - flux-system
        - ingress-${cluster_name}
        - ${cluster_name}-camel-k
        - ${cluster_name}-flowable
        - ${cluster_name}-keycloak
        - ${cluster_name}-openbao
        - ${cluster_name}-rabbitmq
        - ${cluster_name}-seaweedfs
        - ${cluster_name}-supabase
        - ${cluster_name}-valkey
        - ${cluster_name}-centrifugo
        - ${cluster_name}-superset
