apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devops-sso-tls
  namespace: devops-keycloak
spec:
  secretName: devops-sso-tls
  issuerRef:
    name: internal-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - sso-admin.hadeed.dev
    - sso.hadeed.dev
    - devops-sso-service.devops-keycloak.svc.cluster.local