apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "keycloak-db-push-secret"
  namespace: devops-db
spec:
  refreshInterval: "0"
  secretStoreRefs:
  - name: devops-bao
    kind: ClusterSecretStore
  selector:
    secret:
      name: devops-db-app
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: dynamic/keycloak/keycloak-db
        property: password
