apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "keycloak-db-secret"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: devops-bao
    kind: ClusterSecretStore
  target:
    name: keycloak-db
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        host: devops-db-rw.devops-db.svc.cluster.local
        port: "5432"
        database: keycloak
        username: keycloak
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: dynamic/keycloak/keycloak-db
      property: password
