apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "keycloak-db-secret"
  namespace: ${cluster_name}-keycloak
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: ${cluster_name}-bao
    kind: ClusterSecretStore
  target:
    name: keycloak-db
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        host: ${cluster_name}-supabase-rw.${cluster_name}-supabase.svc.cluster.local
        port: "5432"
        database: keycloak
        username: keycloak
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: dynamic/keycloak/keycloak-db
      property: password
