apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "keycloak-db-secret"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: devops-bao
    kind: ClusterSecretStore
  target:
    name: keycloak-db
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        host: devops-db-rw.devops-db.svc.cluster.local
        port: "5432"
        database: keycloak
        username: keycloak
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: dynamic/keycloak/keycloak-db
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "keycloak-admin"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  refreshPolicy: CreatedOnce
  target:
    name: keycloak-admin
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: keycloak-admin
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "password-generator"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "keycloak-admin"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  secretStoreRefs:
  - name: devops-bao
    kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-admin
  dataTo:
    - storeRef:
        name: devops-bao
        kind: ClusterSecretStore
      remoteKey: dynamic/keycloak/keycloak-admin
