# LeptoStack Base configuration -- DO NOT CHANGE
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: leptostack-base
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: leptostack-base
  url: https://github.com/leptostack-fluxcd/leptostack-base.git
