apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: cert-manager
    - name: trust-manager
    - name: external-secrets
    - name: crossplane
    - name: operators
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/base
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/valkey
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apisix
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/apisix
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apisix-post-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: apisix
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/apisix-post-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/openbao
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-init
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: openbao
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/openbao-init
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-post-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: openbao-init
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/openbao-post-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supabase-pre-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: openbao-post-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/supabase-pre-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-pre-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: supabase-pre-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/keycloak-pre-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: keycloak-pre-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/keycloak
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-post-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/keycloak-post-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supabase
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: supabase-pre-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/supabase
  prune: true
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: keycloak-post-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/rabbitmq
  prune: true
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flowable-pre-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: rabbitmq
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/flowable-pre-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flowable
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: flowable-pre-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/flowable
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: centrifugo
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/centrifugo
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: camel-k
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/camel-k
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: superset
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: keycloak-post-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/superset
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: superset-post-deploy
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: superset
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/superset-post-deploy
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./leptostack/seaweedfs
  prune: true
  wait: false
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: leptostack-config
