---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  namespace: devops-keycloak
  name: devops-sso-service
spec:
  ingressClassName: devops-apisix
  scheme: https
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  namespace: devops-keycloak
  name: keycloak
spec:
  ingressClassName: devops-apisix
  http:
    - name: keycloak
      match:
        hosts:
          - sso.hadeed.dev
        paths:
          - /*
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            headers:
              set:
                X-Forwarded-Proto: https
                X-Forwarded-Port: "443"
                X-Forwarded-Host: sso.hadeed.dev
      backends:
        - serviceName: devops-sso-service
          servicePort: 8443
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  namespace: devops-keycloak
  name: keycloak-admin
spec:
  ingressClassName: devops-apisix
  http:
    - name: keycloak
      match:
        hosts:
          - sso-admin.hadeed.dev
        paths:
          - /*
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            headers:
              set:
                X-Forwarded-Proto: https
                X-Forwarded-Port: "443"
                X-Forwarded-Host: sso-admin.hadeed.dev
      backends:
        - serviceName: devops-sso-service
          servicePort: 8443
