apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: devops-sso
  namespace: devops-keycloak
spec:
  db:
    vendor: postgres
    host: devops-supabase-rw.devops-supabase.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-db
      key: username
    passwordSecret:
      name: keycloak-db
      key: password
  hostname:
    admin: https://sso-admin.hadeed.dev
    hostname: https://sso.hadeed.dev
    strict: true
  http:
    tlsSecret: devops-sso-tls
  ingress:
    enabled: false
  instances: 1
  proxy:
    headers: xforwarded
  unsupported:
    podTemplate:
      spec:
        containers:
          - securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
