apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Deployment
    name: kustomize-controller
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=5s
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --feature-gates=StrictPostBuildSubstitutions=true
- patch: |
    - op: remove
      path: /metadata/labels/pod-security.kubernetes.io~1warn
    - op: remove
      path: /metadata/labels/pod-security.kubernetes.io~1warn-version
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1enforce
      value: restricted
  target:
    kind: Namespace
    labelSelector: app.kubernetes.io/part-of=flux
