---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "openbao-unseal-key"
  namespace: devops-openbao
spec:
  refreshInterval: "0"
  refreshPolicy: CreatedOnce
  target:
    name: openbao-key
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "password-generator"
