apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "cloudflare-creds"
  namespace: cloudflare
spec:
  secretStoreRef:
    name: ${cluster_name}-bao
    kind: ClusterSecretStore
  target:
    name: cloudflare-creds
  data:
  - secretKey: credentials.json
    remoteRef:
      key: static/cloudflare/credentials
      property: credentials.json
