---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: internal-ca-push-secret
  namespace: ${cluster_name}-keycloak
spec:
  refreshInterval: "0"
  secretStoreRefs:
  - name: ${cluster_name}-bao
    kind: ClusterSecretStore
  selector:
    secret:
      name: internal-ca-bundle
  data:
  - match:
      secretKey: ca-certificates.crt
      remoteRef:
        remoteKey: dynamic/keycloak/internal-ca
        property: cert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-provider-credentials
  namespace: ${cluster_name}-keycloak
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: ${cluster_name}-bao
    kind: ClusterSecretStore
  target:
    name: keycloak-provider-credentials
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "client_id": "admin-cli",
            "url": "https://${leptostack_name}-sso-service.${cluster_name}-keycloak.svc.cluster.local:8443",
            "username": "keycloak-admin",
            "password": {{ .password | toJson }},
            "root_ca_certificate": {{ .cert | toJson }}
          }
  data:
  - secretKey: password
    remoteRef:
      key: dynamic/keycloak/keycloak-admin
      property: password
  - secretKey: cert
    remoteRef:
      key: dynamic/keycloak/internal-ca
      property: cert
---
apiVersion: keycloak.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ${cluster_name}-keycloak
  namespace: ${cluster_name}-keycloak
spec:
  credentialsSecretRef:
    key: credentials
    name: keycloak-provider-credentials
