---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "devops-admin-secret"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  refreshPolicy: CreatedOnce
  target:
    name: devops-admin
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: devops-admin
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "password-generator"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "devops-admin-push-secret"
  namespace: devops-keycloak
spec:
  refreshInterval: "0"
  secretStoreRefs:
  - name: devops-bao
    kind: ClusterSecretStore
  selector:
    secret:
      name: devops-admin
  dataTo:
    - storeRef:
        name: devops-bao
        kind: ClusterSecretStore
      remoteKey: dynamic/keycloak/devops-admin
---
apiVersion: user.keycloak.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: devops-admin
  namespace: devops-keycloak
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: devops-keycloak
  forProvider:
    realmId: devops
    username: devops-admin
    email: devops-admin@hadeed.com.sa
    firstName: devops
    lastName: Admin
    emailVerified: true
    enabled: true
    initialPassword:
      - valueSecretRef:
          name: devops-admin
          key: password
        temporary: false
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Group
metadata:
  name: devops-admins
  namespace: devops-keycloak
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: devops-keycloak
  forProvider:
    realmId: devops
    name: devops-admins
    description: "DevOps Administrators"
---
apiVersion: group.keycloak.m.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: devops-admins-roles
  namespace: devops-keycloak
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: devops-keycloak
  forProvider:
    realmId: devops
    groupIdRef:
      name: devops-admins
    exhaustive: false
    roleIds:
      - db06501b-5427-46aa-9b79-e3c800beedf8  # realm-admin from realm-management client
---
apiVersion: user.keycloak.m.crossplane.io/v1alpha1
kind: Groups
metadata:
  name: devops-admin-groups
  namespace: devops-keycloak
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: devops-keycloak
  forProvider:
    realmId: devops
    exhaustive: false
    userIdRef:
      name: devops-admin
    groupIdsRefs:
      - name: devops-admins
