apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-pgcluster
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: devops-openbao-post
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/pgcluster
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
