apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/cert-manager
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  interval: 720m0s
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/trust-manager
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/external-secrets
  prune: true
  wait: false
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/crossplane
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-post
  namespace: flux-system
spec:
  interval: 720m0s
  dependsOn:
    - name: crossplane
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/crossplane/post
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  interval: 720m0s
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: leptostack-base
  serviceAccountName: kustomize-controller
  path: ./infrastructure/operators
  prune: true
  wait: false
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-apisix
  namespace: flux-system
spec:
  interval: 720m0s
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/apisix
  prune: false
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-apisix-post
  namespace: flux-system
spec:
  interval: 720m0s
  dependsOn:
    - name: devops-apisix
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/apisix/post
  prune: false
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-openbao
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/openbao
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-openbao-init
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: devops-openbao
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/openbao/init
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-openbao-post
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: devops-openbao-init
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/openbao/post
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-pgcluster
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: devops-openbao-post
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/pgcluster
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-keycloak-pre
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: pgcluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/keycloak/pre
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-keycloak
  namespace: flux-system
spec:
  interval: 720m0s
  timeout: 10m
  dependsOn:
    - name: devops-keycloak-pre
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/keycloak
  prune: true
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: leptostack
