# LeptoStack custom configuration -- Set your cluster configuration and resources here
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leptostack-config
  namespace: flux-system
data:
  cluster_name: local
  leptostack_domain: minikube.test
  leptostack_name: portal
  leptostack_smtp_server: ""
  leptostack_smtp_port: ""
  leptostack_smtp_username: ""
  leptostack_smtp_password: ""
  apisix_lb_ip: 192.168.49.100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.49.100-192.168.49.110
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: internal-issuer
    k8s.apisix.apache.org/plugin-config-name: registry-plugin-config
  name: registry-ingress
  namespace: kube-system
spec:
  ingressClassName: local-apisix
  tls:
    - hosts:
        - registry.minikube.test
      secretName: registry-tls
  rules:
    - host: registry.minikube.test
      http:
        paths:
          - backend:
              service:
                name: registry
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  namespaceSelector: has(kubernetes.io/metadata.name) && kubernetes.io/metadata.name not in {"kube-system"}
  types:
    - Ingress
    - Egress
  egress:
    - action: Allow
