# LeptoStack custom configuration -- Set your cluster configuration and resources here
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leptostack-config
  namespace: flux-system
data:
  cluster_name: dev
  leptostack_domain: hadeed.dev
  leptostack_name: portal-dev
  leptostack_smtp_server: ""
  leptostack_smtp_port: ""
  leptostack_smtp_username: ""
  leptostack_smtp_password: ""
  apisix_lb_ip: 192.168.49.100
